### ISSUE TITLE
let systemd auto-save config

### ISSUE THREAD

**Issue by danrl** [danrl/ratools#15]
It would be great if ratools-rad.service could load and save the config automatically.

Loading:
* start `rad`
* check if `/etc/ratools/rad.conf` exists
  * run `ractl < /etc/ratools/rad.conf`

Saving:
* run `ractl > /etc/ratools/rad.conf`
* stop `rad`

/cc @florianl

**Comment by florianl** [comment]
For loading please take a look at pull request https://github.com/danrl/ratools/pull/17

**Comment by danrl** [comment]
Thanks! What happens if `/etc/ratools/rad.conf` does not exists?

**Comment by florianl** [comment]
Stop!
I missed the important part. Checking if the file exists...

**Comment by florianl** [comment]
Fixed in https://github.com/danrl/ratools/pull/18
